FROM maven:3.9.8-eclipse-temurin-21 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:21-jdk
COPY --from=build /target/azure-basic-app-0.0.1-SNAPSHOT.jar azure-basic-app.jar
EXPOSE 8080
ENTRYPOINT [ "java","-jar","azure-basic-app.jar" ]